---
title: "Behavioral Proximity Models & fMRI Activity Modulation"
author: "Mengzhe Wei"
date: "`r Sys.Date()`"
output:
  pdf_document: default
---
# Proximity Results
### This file is to analyze MARCER data's proximity 
Notes: 
dACC parcel IDs: 
7Networks_LH_SalVentAttn_Med_1 P107
7Networks_LH_SalVentAttn_Med_2 P108
7Networks_LH_SalVentAttn_Med_4 P110
7Networks_RH_SalVentAttn_Med_1 P311
7Networks_RH_SalVentAttn_Med_2 P312
I combined it all together. 
In the coged behavioral file, starting trial 46 is the first run of coged. 
```{r setup, eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
# This is originally meant to be on the server, but since my server isn't allowing tidyverse I moved it to git.
rm(list=ls())
options(warnPartialMatchDollar=TRUE);   # safety option
#Packages
library(RNifti);library(boxr);library(lme4); library(knitr); library(tidyverse)
box_auth(); 
wustl.box <- TRUE;
fMRI.path <- "/scratch2/weie/COGED_CODE/np2_trial/np2trialwise/"
out.path <-"/scratch2/weie/COGED_CODE/np2_trial/np2analysis/"
atlas.path <- "/data/MARCER/ATLASES/";  
afni.path <- "/usr/local/pkg/afni_22/";   # path to the afni function executables
dir.desc <- "20230714test";  
sub.tbl <- read.table(paste0("/scratch2/weie/COGED_CODE/", dir.desc, "_subjectSet.txt"), stringsAsFactors=FALSE); 
sub.ids <- sub.tbl$sub.id[which(sub.tbl$COGED_CatchNonCatch == TRUE)]
behavior.path <- box_ls('148056179835') 
time.ids <- c("eval","dm")
parcel.ids <- c(107,108,110,311,312)
```

```{r dataset, eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
#Compile a dataset with all choice behavior, proximity, and fMRI activity
col.names <- c("subID","trial","RT","choice","Task","proximity","reward","eval.107","eval.108","eval.110","eval.311","eval.312","dm.107","dm.108","dm.110","dm.311","dm.312","eval.dACC","dm.dACC")
tbl.all <- array(NA,c(36*3*length(sub.ids), length(col.names)), dimnames=list(NULL,col.names))
tbl.all[,1] <- rep(sub.ids,each = 108)
tbl.all[,2] <- rep(1:108)
for (sid in 1:length(sub.ids)) { #sid <- 1
  file.name <- paste0("coged-MARCER-fMRI-",sub.ids[sid],"-converted.csv")
  file.id <- box_search(file.name)
  behavior.data <- box_read(file.id)
  tbl.all[((sid-1)*108+1):(108*sid),(3:7)] <- as.matrix(behavior.data[46:153,c("choiceRT","choice","hardTask","proximityValue","rewardAmount")])
  for (tid in 1:length(time.ids)) { # tid<-1
    fMRI.table <- read.delim(paste0(fMRI.path, "COGED_np2_trialwise_", time.ids[tid], "_sub", sub.ids[sid], ".txt"),header=FALSE)
    tbl.all[((sid-1)*108+1):(108*sid),(8+5*(tid-1)):(12+5*(tid-1))] <- as.matrix(fMRI.table[,parcel.ids])
    tbl.all[((sid-1)*108+1):(108*sid),(18+tid-1)] <- apply(fMRI.table[,parcel.ids], 1, mean, na.rm=TRUE)
  }
}
write.table(tbl.all,file = paste0(out.path, "COGED_trialwise_data.txt"), sep = "\t", row.names = FALSE, col.names = TRUE)

# # We need to mutate: 
# WM.coged.fmri %>% filter(trial > 45) %>% filter(choice != 9) %>%
#   mutate(choseHard = if_else((choice == 1), 0, 1), #choose 1 is easy, choose 2 is hard, choose 9 is NA

```


```{r choice_activity, warning=FALSE, message=FALSE}
rm(list=ls())
library(lme4); library(knitr); library(tidyverse)
# Clean up model
data <- read.delim("COGED_trialwise_data.txt", header = TRUE)
behavior <- data %>%
  filter(choice !=9) %>%
  mutate (choiceCode = if_else(choice == 1, 1, 0),#1 is choosing easy, 2 is choosing hard. So after recoding, 1 is easy, 0 is hard. As proximity goes higher, people should be more biased to choose the easier option.
         loadCode = factor(Task, levels = c(1,2,3), labels = c(-1,0,1)),
         rewardCode = factor(reward, levels = c(2,3,4), labels = c(-1,0,1)))
behavior$loadCode <- as.numeric(as.character(behavior$loadCode))
behavior$rewardCode <- as.numeric(as.character(behavior$rewardCode))

# Behavioral choice model
prox.choice <- glmer(data = behavior, choiceCode ~ proximity + rewardCode + loadCode + (proximity|subID), family = "binomial")
summary(prox.choice) #As expected, the higher the proximity, the more likely people are to choose the easier option. The higher the reward for the harder option, the less likely people are to choose the easier option (p = 0.069). The higher the load of the hard task is, the more likely people are to choose the easier option. 

# dACC activity related to proximity
dm.prox <- glmer(data = behavior, dm.dACC ~ proximity + (proximity|subID), family = "gaussian")
summary(dm.prox) #proximity doesn't predict dACC activity during decision making phase
activity.choice <- glmer(data = behavior, choiceCode~dm.dACC+eval.dACC+proximity+rewardCode+loadCode+(proximity|subID), family = "binomial")
summary(activity.choice) #dACC activity doesn't predict choice behavior
activity <- glmer(data = behavior, dm.dACC ~ eval.dACC + (proximity|subID), family = "gaussian")
summary(activity) #the activity during evaluation phase does predict the activity during decision making phase
activity.dm <- glmer(data = behavior, dm.dACC ~ eval.dACC +rewardCode+loadCode+ (proximity|subID), family = "gaussian")
summary(activity.dm) #It seems that the load predicts lower decision making phase activity
activity.eval<- glmer(data = behavior, eval.dACC ~ rewardCode+loadCode+ (1|subID), family = "gaussian")
summary(activity.eval) #reward or load doesn't predict dACC's evaluation activity
```